### ISSUE TITLE
Field Overrides

### ISSUE THREAD

**Issue by odama626** [tonyketcham/flatbread#26]
As a user I would like to be able to specify custom overrides for fields for example:

- having a relative url in a file that needs to be prefixed for storage
- processing an image path into a srcset (think gatsby-image or svimg)

This could be achieved by using apollo's custom scalar logic and defining it in the config
https://www.apollographql.com/docs/apollo-server/v2/schema/custom-scalars/

```js
//flatbread.config.js

function processImage(config) {
  return new GraphQLScalarType({
    name: 'ImageSrcSet'
    ...
  })
}

export default defineConfig({
  ...
  // scalars is an array of Apollo's GraphQLScalarType
  scalars: [processImage(), fixUrls()],

  content: [
    ...
    {
      path: 'content/markdown/authors',
      collection: 'Author',
      refs: {
        friend: 'Author'
      }
      overrides: [
        // process field image
        {
          field: 'image',
          scalar: 'ImageSrcSet',
          resolver: ...
        }
      ]
    }
  ]
```

if a scalar is listed and aligns with a field in the data, the specified type is used

other considerations: (ideas on syntax?)

```yaml
// authors/daes.yaml
name: Daes
skills:
  sports: 90
enjoys:
  - cats
  - coffee
array:
  - field: test
array2:
  - object:
      field: test

```

- override field syntax (object based)
  - `name`
  - `skills: 'sports'`
  - `'enjoys'`
  - `array: ['field']`
  - `array2: [{ object: 'field' }]`
